describe('register case', () => {
    it ('valid credentials', () => {
        cy.visit ('https://gallery-app.vivifyideas.com/')
        cy.get(':nth-child(2) > .nav-link').click()
        cy.get('#first-name').type('testiranje')
        cy.get('#last-name').type('testiranje')
        cy.get('#email').type('testiranje@gmail.com')
        cy.get('#password').type('testiranje12345')
        cy.get('#password-confirmation').type('testiranje12345')
        cy.get('.form-check-input').click()
        cy.get('.btn').click()
    })
    it ('invalid first name', () => {
        cy.visit ('https://gallery-app.vivifyideas.com/')
        cy.get(':nth-child(2) > .nav-link').click()
        cy.get('#first-name').type('testir@nje')
        cy.get('#last-name').type('testiranje')
        cy.get('#email').type('testira@gmail.com')
        cy.get('#password').type('testiranje12345')
        cy.get('#password-confirmation').type('testiranje12345')
        cy.get('.form-check-input').click()
        cy.get('.btn').click()
    })
    it ('ivalid last name', () => {
        cy.visit ('https://gallery-app.vivifyideas.com/')
        cy.get(':nth-child(2) > .nav-link').click()
        cy.get('#first-name').type('testi')
        cy.get('#last-name').type('testir@nje')
        cy.get('#email').type('testi@gmail.com')
        cy.get('#password').type('testiranje12345')
        cy.get('#password-confirmation').type('testiranje12345')
        cy.get('.form-check-input').click()
        cy.get('.btn').click()
    })
    it ('ivalid email', () => {
        cy.visit ('https://gallery-app.vivifyideas.com/')
        cy.get(':nth-child(2) > .nav-link').click()
        cy.get('#first-name').type('testi')
        cy.get('#last-name').type('testir@nje')
        cy.get('#email').type('testigmail.com')
        cy.get('#password').type('testiranje12345')
        cy.get('#password-confirmation').type('testiranje12345')
        cy.get('.form-check-input').click()
        cy.get('.btn').click()
    })
    it ('ivalid password', () => {
        cy.visit ('https://gallery-app.vivifyideas.com/')
        cy.get(':nth-child(2) > .nav-link').click()
        cy.get('#first-name').type('testi')
        cy.get('#last-name').type('testir@nje')
        cy.get('#email').type('testitesti@gmail.com')
        cy.get('#password').type('@#$testiranje12345')
        cy.get('#password-confirmation').type('@#$testiranje12345')
        cy.get('.form-check-input').click()
        cy.get('.btn').click()
    })
})